version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 4.a, < 5"
  - dependency-name: pytest
    versions:
    - ">= 5.a, < 6"
  - dependency-name: idna
    versions:
    - "2.10"
  - dependency-name: urllib3
    versions:
    - 1.26.2
